
on:
  push:
    tags:
      - "v*.*.*"

name: release

permissions:
  id-token: write
  contents: write

jobs:
  pypi:
    name: Build, sign and publish release to GitHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: install poetry
      run: python -m pip install poetry

    - name: install sigstore
      run: python -m pip install sigstore

    - name: build
      run: python -m poetry build

    - name: sign
      run: |
        mkdir -p signing-artifacts
        for dist in dist/*; do
          dist_base="$(basename "${dist}")"

          python -m sigstore sign "${dist}" \
            --output-signature signing-artifacts/"${dist_base}.sig" \
            --output-certificate signing-artifacts/"${dist_base}.crt"

          python -m sigstore verify "${dist}" \
            --cert "signing-artifacts/${dist_base}.crt" \
            --signature "signing-artifacts/${dist_base}.sig" \
            --cert-oidc-issuer https://token.actions.githubusercontent.com
        done

    - name: upload artifacts to github
      uses: softprops/action-gh-release@v1
      with:
        # dist/ -> wheel and source tarball
        # signing-artifacts/ -> signatures and certificates.
        files: |
          dist/*
          signing-artifacts/*
